FROM node

# 修改解释器为bash（解决dash无法回退历史命令等问题）
RUN echo no | dpkg-reconfigure dash

RUN npm config set registry https://registry.npm.taobao.org

RUN cd ~/ && mkdir .ssh && cd .ssh && echo '' | ssh-keygen

ARG NODE_VERSION=stable
RUN npm install -g n
RUN n ${NODE_VERSION}