# default install php8.0
FROM php:8.0-fpm

MAINTAINER Mike mikehub@aliyun.com
WORKDIR /var/www

# 修改解释器为bash（解决dash无法回退历史命令等问题）
RUN echo no | dpkg-reconfigure dash

# 更换源
RUN mv /etc/apt/sources.list /etc/apt/sources.list.bak
COPY config/sources.list /etc/apt
RUN apt-get clean all && apt-get update -y

RUN apt-get install vim -y \
    && apt-get install wget -y \
    && apt-get install cmake -y \
    && apt-get install git -y \
    && apt-get install zip -y

# install compser
RUN php -r "copy('https://install.phpcomposer.com/installer', 'composer-setup.php');"
RUN php composer-setup.php
RUN php -r "unlink('composer-setup.php');"
RUN mv composer.phar /usr/local/bin/composer
RUN composer config -g repo.packagist composer https://mirrors.aliyun.com/composer

# install php extend
RUN cp /usr/local/etc/php/php.ini-production /usr/local/etc/php/php.ini

RUN pecl install igbinary && docker-php-ext-enable igbinary
RUN apt-get install libzstd-dev -y
RUN pecl install redis && docker-php-ext-enable redis

# install opessl
#RUN echo y | apt-get install libssl1.1=1.1.1n-0+deb11u3
RUN echo y | apt-get install libssl-dev

RUN wget https://github.com/alanxz/rabbitmq-c/archive/refs/tags/v0.13.0.tar.gz
RUN tar -zxvf v0.13.0.tar.gz
RUN cd rabbitmq-c-0.13.0 && mkdir build && cd build \
    && cmake -DCMAKE_INSTALL_PREFIX=/usr/local/rabbitmq-c .. \
    && cmake --build . --target install
RUN apt-get install librabbitmq-dev -y
RUN echo "/usr/local/rabbitmq-c" | pecl install amqp \
    && docker-php-ext-enable amqp
RUN rm -rf v0.13.0.tar.gz rabbitmq-c-0.13.0

RUN echo y | pecl install swoole && docker-php-ext-enable swoole

RUN docker-php-ext-install pcntl

RUN docker-php-ext-install pdo_mysql